### ISSUE TITLE
Error getting chat-with-rendezvous (proto.InternalMessageInfo)

### ISSUE THREAD

**Issue by Wei-1** [libp2p/go-libp2p-examples#11]
While running:

```bash
go get github.com/libp2p/go-libp2p-examples/chat-with-rendezvous
```

I encounter this error:

```bash
# github.com/libp2p/go-libp2p-record/pb
/Users/weichen/go/src/github.com/libp2p/go-libp2p-record/pb/record.pb.go:68:28: undefined: proto.InternalMessageInfo
```

Based on these issues:

https://github.com/grpc/grpc-go/issues/2095
https://github.com/google/go-genproto/issues/77

The first thing that I should try is:

```bash
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
```

But after getting the new `proto` and `protoc-gen-go`, I still get the same error.

Then I try to delete the current protobuf src dir based on this issue https://github.com/golang/protobuf/issues/642

But apparently, it still doesn't help. (still get the same error while running the first script)

The current environment that I am using is `go1.11`, which is the latest version of Go already.

**Comment by upperwal** [comment]
Best and fastest solution is to remove everything in GOPATH/src/ and run 

```go get -d github.com/libp2p/go-libp2p-examples/...```

I tried 
```
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
```
with the same error.

or try removing everything from github.com/golang/protobuf and try running ```go get```

**Comment by Wei-1** [comment]
Delete the entire `$GOPATH/src` does solve the issue.
Thanks @upperwal
