### ISSUE TITLE
how to init RendezvousString in chat-with-rendezvous?

### ISSUE THREAD

**Issue by bitcard** [libp2p/go-libp2p-examples#184]
in example chat-with-rendezvous, there is a flag: RendezvousString, does it must set? how to init it? thanks.

**Comment by ChronosX88** [comment]
@bitcard You just need to specify it in console args, for example: `go run chat.go -randezvous <your string>`

**Comment by bitcard** [comment]
> @bitcard You just need to specify it in console args, for example: `go run chat.go -randezvous <your string>`

ok, thank you.
