### ISSUE TITLE
How can i make other peers persist when another peer disconnects

### ISSUE THREAD

**Issue by TheDhejavu** [libp2p/go-libp2p-examples#188]
The current example doesn't demonstrate how other peers can persist when another peer disconnects,. all peers automatically shut down when I disconnect from one

**Comment by jacobheun** [comment]
Which example are you running?

**Comment by TheDhejavu** [comment]
@jacobheun 
this example
https://github.com/libp2p/go-libp2p-examples/tree/master/chat-with-rendezvous
