### ISSUE TITLE
Add builds to each example

### ISSUE THREAD

**Issue by petroav** [libp2p/go-libp2p-examples#31]
When going through the examples I found myself creating a `package.json` for each example using `gx`. Unless the imports in the examples are re-written the binaries don't build. I'd like to upstream the Makefiles and the `package.json` files and save other users the time.

Let me know if you think this is a good/bad idea, thanks! @vyzo @raulk @Stebalien

**Comment by Stebalien** [comment]
The binaries *should* build without gx. That's why we aren't using it (we don't want to make users think they *have* to use gx to use libp2p).

Make sure you have a *clean* gopath.

**Comment by raulk** [comment]
Agree with @stebalien. I’d prefer to avoid imposing our world view (gx) to Go developers, unless inevitable. It seems unnecessary in this case, and what you’re seeing is probably the product of some dependency not being clean in hour gopath.

Try running a `go get -d -u ./...`. That’ll update your local deps and scream in case of local changes.

**Comment by petroav** [comment]
@Stebalien @raulk yep, that makes sense. I definitely don't have a clean gopath as I've checked out and built the other repos. I also got confused by this comment https://github.com/libp2p/go-libp2p-examples/blob/master/http-proxy/proxy.go#L14.

Should I update the README warning other developers of this (not having a clean gopath) and removing the above comment?
