### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bloodchen** [libp2p/go-libp2p-examples#52]
Trying to build an example but got the following errors,

…
go: finding github.com/libp2p/go-stream-muxer v3.0.1+incompatible
go: github.com/libp2p/go-libp2p-transport-upgrader@v0.1.16: unknown revision v0.1.16
go: finding github.com/libp2p/go-libp2p-routing v2.7.1+incompatible
go: github.com/libp2p/go-libp2p-interface-connmgr@v0.0.21: unknown revision v0.0.21
go: finding github.com/libp2p/go-libp2p-nat v0.8.8
go: github.com/libp2p/go-conn-security@v0.1.15: unknown revision v0.1.15
go: finding github.com/libp2p/go-addr-util v2.0.7+incompatible
go: github.com/libp2p/go-mplex@v0.2.30: unknown revision v0.2.30
go: finding github.com/libp2p/go-libp2p-peer v2.4.0+incompatible
go: github.com/multiformats/go-multiaddr@v1.4.0: unknown revision v1.4.0
go: finding github.com/libp2p/go-libp2p-metrics v2.1.7+incompatible
go: github.com/libp2p/go-libp2p-crypto@v2.0.5+incompatible: unknown revision v2.0.5
go: finding github.com/libp2p/go-libp2p-peerstore v2.0.6+incompatible
go: github.com/multiformats/go-multiaddr-net@v1.7.1: unknown revision v1.7.1
go: finding github.com/libp2p/go-libp2p-host v3.0.15+incompatible
go: github.com/libp2p/go-libp2p-swarm@v3.0.22+incompatible: unknown revision v3.0.22
go: finding github.com/libp2p/go-libp2p-record v4.1.7+incompatible
go: github.com/libp2p/go-stream-muxer@v3.0.1+incompatible: unknown revision v3.0.1
go: github.com/libp2p/go-libp2p-routing@v2.7.1+incompatible: unknown revision v2.7.1
go: github.com/libp2p/go-libp2p-peer@v2.4.0+incompatible: unknown revision v2.4.0
go: github.com/libp2p/go-libp2p@v6.0.29+incompatible: unknown revision v6.0.29
go: github.com/libp2p/go-libp2p-nat@v0.8.8: unknown revision v0.8.8
go: github.com/libp2p/go-libp2p-record@v4.1.7+incompatible: unknown revision v4.1.7
go: github.com/libp2p/go-addr-util@v2.0.7+incompatible: unknown revision v2.0.7
go: github.com/libp2p/go-libp2p-metrics@v2.1.7+incompatible: unknown revision v2.1.7
go: github.com/libp2p/go-libp2p-host@v3.0.15+incompatible: unknown revision v3.0.15
go: github.com/libp2p/go-libp2p-peerstore@v2.0.6+incompatible: unknown revision v2.0.6
go: error loading module requirements

**Comment by raulk** [comment]
@bloodchen could you try again? Should be fixed now.

**Comment by bloodchen** [comment]
The same error. I re-download the whole rep as ZIP and run ‘make’ in go-libp2p-examples folder.
…
go: github.com/libp2p/go-libp2p-host@v3.0.15+incompatible: unknown revision v3.0.15
go: finding github.com/libp2p/go-buffer-pool v0.1.3
go: github.com/libp2p/go-libp2p-peerstore@v2.0.6+incompatible: unknown revision v2.0.6
go: finding github.com/libp2p/go-conn-security v0.1.15
go: github.com/libp2p/go-libp2p-kbucket@v2.2.12+incompatible: unknown revision v2.2.12
go: github.com/libp2p/go-msgio@v0.0.6: unknown revision v0.0.6
go: github.com/libp2p/go-libp2p-netutil@v0.4.12: unknown revision v0.4.12
go: github.com/libp2p/go-addr-util@v2.0.7+incompatible: unknown revision v2.0.7
go: github.com/libp2p/go-libp2p-peer@v2.4.0+incompatible: unknown revision v2.4.0
go: github.com/libp2p/go-stream-muxer@v3.0.1+incompatible: unknown revision v3.0.1
go: github.com/libp2p/go-libp2p-interface-pnet@v3.0.0+incompatible: unknown revision v3.0.0
go: github.com/libp2p/go-buffer-pool@v0.1.3: unknown revision v0.1.3
go: github.com/libp2p/go-libp2p-blankhost@v0.3.15: unknown revision v0.3.15
go: github.com/libp2p/go-conn-security@v0.1.15: unknown revision v0.1.15
go: error loading module requirements
