### ISSUE TITLE
Any example using stream multiplexers? 

### ISSUE THREAD

**Issue by jeshocarmel** [libp2p/go-libp2p-examples#61]
Would be really helpful to have an example using ymux or mplex

**Comment by upperwal** [comment]
ymux and mplex are used internally whenever you create a new stream. So, you are [already using them](https://github.com/libp2p/go-libp2p/blob/f2cdce7b0cae71b5e584c12e84ea7599669894c4/defaults.go#L24-L31).

**Comment by jeshocarmel** [comment]
Great. My bad I didn't notice that. Implicit implementation it is then. Thanks

**Comment by upperwal** [comment]
👍
