### ISSUE TITLE
http-proxy failed when visit https website

### ISSUE THREAD

**Issue by fxsjy** [libp2p/go-libp2p-examples#77]
libp2p is cool, I am studying it , and want to use the example "http-proxy" to build my own proxy.

However, I find it only works for http website, not for the https website.

I check the code, which use DefaultTransport to forward https request. And, I am not sure whether the problem occurs here.

**Comment by jsign** [comment]
I think #83 will help with that.

**Comment by fxsjy** [comment]
@jsign ,  the proxy should handle "CONNECT" method, otherwise the remote https server can't understand "CONNECT"
